# Setup
title: Hi, I'm Max
description: >-
  I'm an undergraduate senior studying computer science at the University of Michigan.
url: https://mxmoss.me
paginate: 5
paginate_path: /blog/index.html
email: mossberg.max@gmail.com
avatar: head_shot.JPG
cover_image: mt_huang_shan.jpg

# remote_theme: vszhub/not-pure-poole

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: mxmossy
  card: summary
logo: logo.png
social:
  name: Max Mossberg
  links:
    - https://twitter.com/mxmossy
    - https://github.com/mxmossy
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx


# Blog Author info
author:
  name: Max Mossberg
  url: https://github.com/mxmossy/
  email: mossberg.max@gmail.com
twitter_username: mxmossy
github_username: mxmossy

# remote_theme: vszhub/not-pure-poole